#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:05:00
#PBS -A open
#PBS -j oe
#PBS -N fidelity_viewer

module use /gpfs/group/mnh5174/default/sw/modules
module load python/3.6.3
module load fsl/6.0.1

code_dir="code"

# run the script to output the results of the fidelity checks in a human-readable manner
python ${repo_loc}/mri_fidelity_checks/${code_dir}/substatus.py ${loc_root}/fidelity_output_data "$sub" && date "+%m %d %y @ %H:%M" > ${loc_root}/bids/sub-${sub}/.fidelity.complete
