#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:05:00
#PBS -A mnh5174_c_g_sc_default
#PBS -j oe
#PBS -N fidelity_viewer

module use /gpfs/group/mnh5174/default/sw/modules
module load python/3.6.3
module load fsl/6.0.1

code_dir="code"

# run the script to output the results of the fidelity checks in a human-readable manner
python ${repo_loc}/mri_fidelity_checks/${code_dir}/substatus.py $fidelity_dir "$sub"
