#!/usr/bin/env Rscript

library(jsonlite)

#read in command line arguments.
args <- commandArgs(trailingOnly = FALSE)

scriptpath <- dirname(sub("--file=", "", grep("--file=", args, fixed=TRUE, value=TRUE), fixed=TRUE))
argpos <- grep("--args", args, fixed=TRUE)
if (length(argpos) > 0L) {
   args <- args[(argpos+1):length(args)]
} else {
  args <- c()
}

if (length(args) == 0L) { stop("Expect at least one top-level subject directory") }

#needs to be a path to top of subject directory (can also be multiple paths)

fpath <- args
#fpath <- "/gpfs/group/mnh5174/default/lab_resources/installers/heudiconv/test/sub-040"

if (!all(fex <- file.exists(fpath))) { stop("Cannot locate dir: ", fpath[!fex]) }

for (fp in fpath) {  
  bold_files <- list.files(path=file.path(fp, "func"), pattern=".*_bold\\.nii\\.gz", full.names=TRUE)
  fmap_files <- list.files(path=file.path(fp, "fmap"), pattern=".*_epi\\.nii\\.gz", full.names=TRUE)

  for (f in fmap_files) {
    jfile <- sub(".nii.gz", ".json", f, fixed=TRUE)
    j <- read_json(path=jfile)
    j$IntendedFor <- bold_files
    message("In ", jfile, ", adding IntendedFor: ", paste(bold_files, collapse=", "))
    write_json(j, path=jfile, pretty=TRUE, auto_unbox=TRUE, digits=NA)
  }
}
